#!/usr/bin/env node
'use strict'

/**
 * Module dependencies
 */
const minimist = require('minimist')
const update = require('update-notifier')
const app = require('./lib/app')
// toxic string prototype to use color
require('colorful').toxic()

/**
 * Package info
 */
const pkg = require('./package')

/**
 * Run notifier
 */
update({pkg}).notify()

/**
 * Parse cli arguments
 */
const argv = minimist(process.argv.slice(2), {'--': true})

/**
 * Initial app
 */
app(argv)
